### ISSUE TITLE
Bintray is gone

### ISSUE THREAD

**Issue by sebthom** [abstratt/eclipsegraphviz#10]
The plugin cannot be installed any longer from https://dl.bintray.com/abstratt-oss/abstratt-oss/com/abstratt/eclipsegraphviz/com.abstratt.eclipsegraphviz.repository/

Is there an alternative location where **com.abstratt.eclipsegraphviz.repository-2.9.0.zip** can be found?

**Comment by abstratt** [comment]
Apologies for missing this report, missed my notifications for a while. 

I updated the instructions with the new locations. Please let me know if they don't work for you.
