### ISSUE TITLE
Update Site not working - certificate expired

### ISSUE THREAD

**Issue by sebthom** [abstratt/eclipsegraphviz#15]
https://abstratt.com/textuml/update/

"Websites prove their identity via certificates, which are valid for a set time period. The certificate for abstratt.com expired on 1/6/2023."

Wouldn't it be better if you host the update site on github pages?

**Comment by sebthom** [comment]
Unfortunately the certificate is expired again.

![image](https://github.com/abstratt/eclipsegraphviz/assets/426959/ea8ada46-ec02-4044-8144-9e206952dbd9)

**Comment by abstratt** [comment]
Sorry. Fixed now.
