### ISSUE TITLE
Save image to SVG

### ISSUE THREAD

**Issue by lemmy** [abstratt/eclipsegraphviz#5]
JPG, PNG, GIF, TIF, BMP are all great image formats, but the list is short of a vector graphics format. dot can directly save as SVG.

https://en.wikipedia.org/wiki/Scalable_Vector_Graphics

**Comment by abstratt** [comment]
Will look into it.

**Comment by abstratt** [comment]
[Build 436](https://textuml.ci.cloudbees.com/job/textuml-toolkit/) of the TextUML Toolkit should include the fix. SVG and DOT are now supported.
