### ISSUE TITLE
Update site location not working behind corporate proxy

### ISSUE THREAD

**Issue by jgsuess** [abstratt/eclipsegraphviz#6]
in
Version: Neon.2 Release (4.6.2)
Build id: 20161208-0600
both versions of setting up the tool (marketplace, direct jar URL) do not work.

**Comment by abstratt** [comment]
Please provide the errors logged during a failed install. I just tried it and it worked fine for me, no errors whatsoever (even though it was quite slow).

![image](https://cloud.githubusercontent.com/assets/2187522/24729953/105c7c8c-1a37-11e7-8846-2fb92f3388d2.png)

**Comment by abstratt** [comment]
@jgsuess Saw your comment on the Marketplace:

> This plugin is offered on the marketplace using jar:// URL that ends in a zip file for the site. Most corporate proxies will block this access from automated user agents. This probably means this plugin cannot be installed in most major companies. To address this, the project might want to stage a regular P2 repository layout.

JAR URLs are resolved inside the JVM, your proxy will not see a request for that URL, but for the encapsulated URL only. So, for this JAR URL:

    jar:http://repository-textuml.forge.cloudbees.com/snapshot/com/abstratt/eclipsegraphviz/com.abstratt.eclipsegraphviz.repository/2.2.201606/com.abstratt.eclipsegraphviz.repository-2.2.201606.zip!/

the actual URL Eclipse will try to hit is:

    http://repository-textuml.forge.cloudbees.com/snapshot/com/abstratt/eclipsegraphviz/com.abstratt.eclipsegraphviz.repository/2.2.201606/com.abstratt.eclipsegraphviz.repository-2.2.201606.zip

Did you manage to access the error log? (Window > View > Error Log, or <workspace>/.metadata/.log)? That would help in understanding what is going on.

Also, if you are having connectivity issues, a workaround is to download the update site (http URL above), and install EclipseGraphviz from the locally download (zipped) update site.

**Comment by jgsuess** [comment]
So the url being resolved is not for a zip archive, the response does not
identify the content type as a zip, and the data being retrieved is not a
zip file? Under any of those circumstance the proxy would probably block.
What I am trying to say is that a zip file provided over http that is not
on a whitelist is likely to be blocked.

I will provide detailed error once at work.

Thanks for the prompt response!

JG

**Comment by abstratt** [comment]
@jgsuess  It is a zip file:

```
$ curl -vI http://repository-textuml.forge.cloudbees.com/snapshot/com/abstratt/eclipsegraphviz/com.abstratt.eclipsegraphviz.repository/2.2.201606/com.abstratt.eclipsegraphviz.repository-2.2.201606.zip
*   Trying 184.73.235.178...
* Connected to repository-textuml.forge.cloudbees.com (184.73.235.178) port 80 (#0)
> HEAD /snapshot/com/abstratt/eclipsegraphviz/com.abstratt.eclipsegraphviz.repository/2.2.201606/com.abstratt.eclipsegraphviz.repository-2.2.201606.zip HTTP/1.1
> Host: repository-textuml.forge.cloudbees.com
> User-Agent: curl/7.47.0
> Accept: */*
> 
< HTTP/1.1 200 OK
HTTP/1.1 200 OK
< Date: Thu, 06 Apr 2017 20:00:51 GMT
Date: Thu, 06 Apr 2017 20:00:51 GMT
< Server: Apache/2.4.10 (Unix) SVN/1.8.10
Server: Apache/2.4.10 (Unix) SVN/1.8.10
< Last-Modified: Thu, 06 Apr 2017 14:06:59 GMT
Last-Modified: Thu, 06 Apr 2017 14:06:59 GMT
< ETag: "16f30-54c8005c3e678"
ETag: "16f30-54c8005c3e678"
< Accept-Ranges: bytes
Accept-Ranges: bytes
< Content-Length: 94000
Content-Length: 94000
< Content-Type: application/zip
Content-Type: application/zip

< 
* Connection #0 to host repository-textuml.forge.cloudbees.com left intact
```

Also, if I grab the file:
```
curl -v http://repository-textuml.forge.cloudbees.com/snapshot/com/abstratt/eclipsegraphviz/com.abstratt.eclipsegraphviz.repository/2.2.201606/com.abstratt.eclipsegraphviz.repository-2.2.201606.zip > test.zip

unzip -t test.zip 
Archive:  test.zip
    testing: features/                OK
    testing: plugins/                 OK
    testing: artifacts.xml.xz         OK
    testing: content.xml.xz           OK
    testing: artifacts.jar            OK
    testing: content.jar              OK
    testing: features/com.abstratt.eclipsegraphviz.feature_2.2.201606.201704061406.jar   OK
    testing: p2.index                 OK
    testing: plugins/com.abstratt.graphviz_2.2.201606.201704061406.jar   OK
    testing: plugins/com.abstratt.imageviewer_2.2.201606.201704061406.jar   OK
    testing: plugins/com.abstratt.pluginutils_2.2.201606.201704061406.jar   OK
    testing: plugins/com.abstratt.content_2.2.201606.201704061406.jar   OK
    testing: plugins/com.abstratt.graphviz.ui_2.2.201606.201704061406.jar   OK
No errors detected in compressed data of test.zip.

```

**Comment by jgsuess** [comment]
And so it probably gets blocked. I assume it is the hosting location that
is the issue. Many proxy Configs in large companies block odd combinations
of UA and destination. One way to block backdoor downloads from their
perspective.

**Comment by abstratt** [comment]
@jgsuess That is unfortunate. If you confirm you can't download the zip file not even directly via the browser (how do you get Eclipse? Would .tgz resolve the issue?), you can try this other URL:

https://github.com/abstratt/eclipsegraphviz/releases/download/2.2.201606.201704061406/com.abstratt.eclipsegraphviz.repository-2.2.201606.zip

which is a GitHub "release" I created to get you unstuck.

**Comment by jgsuess** [comment]
Eclipse downloads are whitelisted. In particular, the delivery server DNS
name.
I'm unsure what UA string eclipse uses when accessing the outside. I would
need that to reproduce.

**Comment by abstratt** [comment]
I believe it uses ECF, which I believe uses Apache HTTP client. But does the UA matter? Are you able to grab the .zip file using a browser?

**Comment by jgsuess** [comment]
Just arrived at work 6.46 am. Booting up and will let you know in about 10
minutes.

**Comment by jgsuess** [comment]
I cannot get the archive using `curl`, but can get it using the browser.

**Comment by jgsuess** [comment]
but eclipse reports:
`Communication with repository at jar:http://repository-textuml.forge.cloudbees.com/snapshot/com/abstratt/eclipsegraphviz/com.abstratt.eclipsegraphviz.repository/2.2.201606/com.abstratt.eclipsegraphviz.repository-2.2.201606.zip!/content.xml.xz failed.`
root cause
`Caused by: java.net.SocketTimeoutException: Read timed out`

**Comment by abstratt** [comment]
Oh, *that* I have seen once in a while as well. At least you have the workaround of downloading the .zip file and installing from the archived update site - right?

**Comment by jgsuess** [comment]
Yes, that works reliably. But I think this issue might turn people off an
otherwise nice tool. a.k.a. I have to do *what* to install it? You must be
kidding...

**Comment by abstratt** [comment]
@jgsuess Thanks for confirming it.

Agree that it is not ideal, but it is what we have for the moment with our current build infrastructure. 

I added to the readme an installation method number 3  explaining the problem and how to work around it. Thanks for helping in understanding it.

**Comment by abstratt** [comment]
Update site now is http based and should work behind a firewall/proxy as well.
